name = "sub021"
main = "src/worker.ts"
compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "settings", id = "89d9725c787d43ee907db1955e6b6ef4" }
]
